SlideInfo.App/Controllers/SlidesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SlideInfo.App.Constants;
using SlideInfo.App.Data;
using SlideInfo.App.Helpers;
using SlideInfo.App.Models;
using SlideInfo.App.Models.SlideViewModels;
using SlideInfo.Core;
using static SlideInfo.App.Constants.ViewConstants;

namespace SlideInfo.App.Controllers
{
    public partial class SlidesController : Controller
    {
        private readonly SignInManager<AppUser> signInManager;
        private readonly SlideInfoDbContext context;
        private readonly ILogger logger;


        public SlidesController(ILogger<SlidesController> logger, SlideInfoDbContext context, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            this.signInManager = signInManager;
            this.logger = logger;
            this.context = context;
        }

        // GET: Slides
        public async Task<IActionResult> Index(int? id, string sortOrder,
            string currentFilter, string searchString)
        {
            if (!signInManager.IsSignedIn(User))
                return RedirectToAction("Login", "Account");

            logger.LogInformation("Getting all slides...");

            ViewData[NAME_SORT_PARAM] = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewData[VENDOR_SORT_PARAM] = sortOrder == "Vendor" ? "Vendor_desc" : "Vendor";
            ViewData[WIDTH_SORT_PARAM] = sortOrder == "Width" ? "Width_desc" : "Width";
            ViewData[HEIGHT_SORT_PARAM] = sortOrder == "Height" ? "Height_desc" : "Height";
            ViewData[CURRENT_FILTER] = searchString;
            ViewData[SLIDE_ID] = null;
            HttpContext.Session.Remove(SLIDE_ID);
            ViewData[HAS_ASSOCIATED_IMAGES] = null;
            ViewData[HAS_COMMENTS] = null;

            var slides = from s in context.Slides.Include(s => s.Comments)
                         select s;

            if (!string.IsNullOrEmpty(searchString))
            {
                slides = slides.Where(s => s.Name.Contains(searchString)
                                           || s.Vendor.Contains(searchString));
            }

            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "Name";
            }

            var descending = false;
            if (sortOrder.EndsWith("_desc"))
            {
                sortOrder = sortOrder.Substring(0, sortOrder.Length - 5);
                @descending = true;
            }

            slides = @descending ?
                slides.OrderByDescending(e => EF.Property<object>(e, sortOrder))
                : slides.OrderBy(e => EF.Property<object>(e, sortOrder));

            var finalSlides = await slides.AsNoTracking().ToListAsync();
            GenerateSlideThumbnails(finalSlides);
            return View(finalSlides);
        }

        // GET: Slides/Display/5
        public async Task<IActionResult> Display(int? id)
        {
            logger.LogInformation("Getting slide {ID} to display...", id);
            if (id == null)
            {
                logger.LogWarning("Slide id was null");
                return NotFound();
            }

            var slide = await context.Slides.FindAsync(id.Value);

            if (slide == null)
            {
                logger.LogError("GetById({ID}) NOT FOUND", id);
                return NotFound();
            }

            HttpContext.Session.Set(SessionConstants.CURRENT_SLIDE, slide);
            ViewData[SLIDE_ID] = slide.Id.ToString();
            HttpContext.Session.SetString(SLIDE_ID, slide.Id.ToString());
            ViewData[SLIDE_NAME] = slide.Name;
            ViewData[HAS_ASSOCIATED_IMAGES] = slide.HasAssociatedImages;
            var comments = context.Comments.Where(c => c.SlideId == id);
            ViewData[HAS_COMMENTS] = comments.Any();

            var osr = new OpenSlide(slide.FilePath);
            var viewModel = new DisplayViewModel(slide.Name, slide.DziUrl, slide.Mpp, osr);

            return View(viewModel);
        }

        // GET: Slides/Properties/5
        public async Task<IActionResult> Properties(int? id, string sortOrder,
            string currentFilter, string searchString, int? pageSize, int? page)
        {
            ViewData[CURRENT_SORT] = sortOrder;
            ViewData[NAME_SORT_PARAM] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData[CURRENT_FILTER] = searchString;

            logger.LogInformation("Getting properties of slide {ID}", id);
            if (id == null)
            {
                return NotFound();
            }

            var slide = await context.Slides.FindAsync(id.Value);
            if (slide == null)
            {
                return NotFound();
            }
            ViewData[SLIDE_ID] = slide.Id.ToString();
            HttpContext.Session.SetString(SLIDE_ID, slide.Id.ToString());
            ViewData[SLIDE_NAME] = slide.Name;
            ViewData[HAS_ASSOCIATED_IMAGES] = slide.HasAssociatedImages;
            var comments = context.Comments.Where(c => c.SlideId == id);
            ViewData[HAS_COMMENTS] = comments.Any();

            var properties = context.Properties.Where(c => c.SlideId == id);

            //filtering
            if (!String.IsNullOrEmpty(searchString))
            {
                logger.LogInformation("Searching for properties containing {searchString}", searchString);
                properties = properties.Where(s => s.Key.Contains(searchString)
                                               || s.Value.Contains(searchString));
            }

            //sorting
            switch (sortOrder)
            {
                case "name_desc":
                    properties = properties.OrderByDescending(s => s.Key);
                    logger.LogInformation("Sorting properties of slide {ID} by name descending", id);
                    break;
                default:
                    logger.LogInformation("Sorting properties of slide {ID} by name", id);
                    properties = properties.OrderBy(s => s.Key);
                    break;
            }

            var defaultPageSize = 15;

            var paginatedProperties = await PaginatedList<Property>.
                CreateAsync(properties.AsNoTracking(), page ?? 1, pageSize ?? defaultPageSize);
            var viewModel = new PropertiesViewModel(slide.Name, paginatedProperties);
            return View(viewModel);
        }

        // GET: Slides/AssociatedImages/5
        public async Task<IActionResult> AssociatedImages(int? id, string imageName)
        {
            logger.LogInformation("Getting associated images of slide {ID}...", id);

            if (id == null)
            {
                return NotFound();
            }

            var slide = await context.Slides.FindAsync(id.Value);

            if (slide == null)
            {
                return NotFound();
            }
            ViewData[SLIDE_NAME] = slide.Name;
            ViewData[SLIDE_ID] = id.ToString();
            HttpContext.Session.SetString(SLIDE_ID, slide.Id.ToString());
            ViewData[HAS_ASSOCIATED_IMAGES] = slide.HasAssociatedImages;
            var comments = context.Comments.Where(c => c.SlideId == id);
            ViewData[HAS_COMMENTS] = comments.Any();
            var osr = new OpenSlide(slide.FilePath);

            if (!String.IsNullOrEmpty(imageName))
            {
                logger.LogInformation("Getting associated image {name} of slide {ID}...", imageName, id);
                var associatedSlide = osr.AssociatedImages[imageName].ToImageSlide();
                var imageUrl = slide.Id + "/" + imageName + ".dzi";

                var displayViewModel = new DisplayViewModel(imageName, imageUrl, 0, associatedSlide);

                return View("Display", displayViewModel);
            }

            var associated = osr.ReadAssociatedImages();

            GenerateAssociatedImagesThumbnails(id.Value, associated);

            var viewModel = new AssociatedImagesViewModel(slide.Name, associated);

            return View(viewModel);
        }

        // GET: Slides/Comments/5
        public async Task<IActionResult> Comments(int? id, string sortOrder,
            string currentFilter, string searchString, int? pageSize, int? page)
        {
            ViewData[CURRENT_SORT] = sortOrder;
            ViewData[DATE_SORT_PARAM] = String.IsNullOrEmpty(sortOrder) ? "Date_desc" : "";
            ViewData[TEXT_SORT_PARAM] = sortOrder == "Text" ? "Text_desc" : "Text";
            ViewData[USER_SORT_PARAM] = sortOrder == "AppUserId" ? "AppUserId_desc" : "AppUserId";
            ViewData[CURRENT_FILTER] = searchString;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData[CURRENT_FILTER] = searchString;

            logger.LogInformation("Getting comments of slide {ID}", id);
            if (id == null)
            {
                return NotFound();
            }

            var slide = await context.Slides.FindAsync(id.Value);
            if (slide == null)
            {
                return NotFound();
            }

            ViewData[SLIDE_ID] = slide.Id.ToString();
            HttpContext.Session.SetString(SLIDE_ID, slide.Id.ToString());
            ViewData[SLIDE_NAME] = slide.Name;
            ViewData[HAS_ASSOCIATED_IMAGES] = slide.HasAssociatedImages;

            var comments = context.Comments.Where(c => c.SlideId == id);
            ViewData[HAS_COMMENTS] = comments.Any();

SlideInfo.App/Views/Shared/_CommentSideBar.cshtml
@using SlideInfo.App.Constants
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <div id="commentSideForm" class="sidenav">
        <form asp-controller="Slides" asp-action="CreateComment" method="post">
            <a href="javascript:void(0)" class="closebtn" onclick="hideCommentForm()">&times;</a>
            <div class="col-xs-12 form-group">
                <label class="sidenav-text">User:</label>
                <input class="form-control" name="commentUserName" type="text" value="@UserManager.GetUserName(User)" readonly>
            </div>

            <div class="col-xs-12 form-group">
                <label class="sidenav-text">Slide name:</label>
                <input class="form-control" name="commentSlideName" type="text" value="@ViewData[ViewConstants.SLIDE_NAME]" readonly>
            </div>

            <div class="col-xs-12 form-group">
                <label class="sidenav-text">Comment:</label>
                <textarea class="form-control" name="commentText" type="text" rows="6" placeholder="Your observations about this slide..." required></textarea>
                <br />
                <input type="submit" value="Submit" class="btn btn-success green-button sidenav-button" />
            </div>
        </form>
    </div>
}

SlideInfo.App/Views/Shared/_Layout.cshtml
@using SlideInfo.App.Constants
@using SlideInfo.App.Helpers
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SlideInfo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet prefetch" href="https://s3-us-west-2.amazonaws.com/s.cdpn.io/104946/animate.min.css">

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/messenger.css" />
        <link rel="stylesheet" href="~/css/ng-notify.min.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/messenger.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/ng-notify.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img alt="" class="img-responsive" src="/images/rounded-info-button.svg" style="display:inline-block; height:30px; margin-top:-5px" /> SlideInfo
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="@Html.IsActive("Home", "Index")">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (ViewData[ViewConstants.SLIDE_ID] != null)
                    {
                        <li class="dropdown @Html.IsSlideChosen("Slides", ViewData["SlideId"] as string)">
                            <a class="dropdown-toggle" data-toggle="dropdown" asp-area="" asp-controller="Slides" asp-action="Index">
                                Slides<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a asp-area="" asp-controller="Slides" asp-action="Index">
                                        All Slides &raquo;
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div class="slide-name">@ViewData[ViewConstants.SLIDE_NAME]</div>
                                </li>
                                <li class="divider"></li>
                                <li class="@Html.IsActive("Slides", "Display")">
                                    <a asp-area="" asp-controller="Slides" asp-action="Display" asp-route-id="@ViewData[ViewConstants.SLIDE_ID]">Display</a>
                                </li>
                                <li class="divider"></li>
                                <li class="@Html.IsActive("Slides", "Properties")">
                                    <a asp-area="" asp-controller="Slides" asp-action="Properties" asp-route-id="@ViewData[ViewConstants.SLIDE_ID]">Properties</a>
                                </li>
                                @if ((bool)ViewData[ViewConstants.HAS_ASSOCIATED_IMAGES])
                                {
                                    <li class="@Html.IsActive("Slides", "AssociatedImages")">
                                        <a asp-area="" asp-controller="Slides" asp-action="AssociatedImages" asp-route-id="@ViewData[ViewConstants.SLIDE_ID]">Associated Images</a>
                                    </li>
                                }
                                @if ((bool)ViewData[ViewConstants.HAS_COMMENTS])
                                {
                                    <li class="@Html.IsActive("Slides", "Comments")">
                                        <a class="@Html.IsDisabled("Slides", ViewData[ViewConstants.HAS_COMMENTS] as string)" asp-area="" asp-controller="Slides" asp-action="Comments" asp-route-id="@ViewData[ViewConstants.SLIDE_ID]">Comments</a>
                                    </li>
                                }
                                <li>
                                    <a href="#" onclick="showCommentSubmitForm()">  Add new comment &raquo; </a>
                                </li>

                            </ul>
                        </li>
                    }
                    @if (ViewData[ViewConstants.SLIDE_ID] == null)
                    {
                        <li class="@Html.IsActiveController("Slides")">
                            <a asp-area="" asp-controller="Slides" asp-action="Index">Slides</a>
                        </li>
                    }
                    <li class="@Html.IsActive("Messenger", "Messenger")"><a asp-area="" asp-controller="Messenger" asp-action="Messenger">Messenger</a></li>
                    <li class="@Html.IsActive("Home", "About")"><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li class="@Html.IsActive("Home", "Contact")"><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    @await Html.PartialAsync("_CommentSideBar.cshtml")
    <div id="main">
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2017 - SlideInfo</p>
            </footer>
        </div>
    </div>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/angular/dist/angular.js"></script>
        <script src="~/lib/underscore/dist/underscore.js"></script>
        <script src="~/lib/ng-notify/dist/ng-notify.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"
                asp-fallback-src="~/lib/angular/dist/angular.min.js"
                asp-fallback-test="window.angular">
        </script>
        <script src="~/lib/underscore/dist/underscore.min.js"></script>
        <script src="~/lib/ng-notify/dist/ng-notify.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        jQuery(function ($) {
            $('.navbar .dropdown').hover(function () {
                $(this).find('.dropdown-menu').first().stop(true, true).slideDown(75);

            }, function () {
                $(this).find('.dropdown-menu').first().stop(true, true).slideUp(75);

            });

            $('.navbar .dropdown > a').click(function () {
                location.href = this.href;
            });

        });

        function showCommentSubmitForm() {
            document.getElementById("commentSideForm").style.width = "300px";
            if (!document.getElementById("displayContainer")) {
                document.getElementById("main").style.paddingLeft = "315px";
                document.getElementById("main").style.overflowX = "hidden";
            }
        }

        function hideCommentForm() {
            document.getElementById("commentSideForm").style.width = "0";
            document.getElementById("main").style.paddingLeft = "15px";
        }
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>